version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"

  - package-ecosystem: "pip"
    directory: "/back-end"
    schedule:
      interval: "weekly"
      day: "wednesday"
    labels:
      - "pip dependencies"
